### ISSUE TITLE
通过 properties 修改的版本无法监测到

### ISSUE THREAD

**Issue by tianyunperfect** [murphysec/murphysec-jetbrains-plugin#1]
以tomcat为例
1、修改属性
![image](https://user-images.githubusercontent.com/23491291/157006157-420b6c7a-ecf1-4ed9-a244-3d2444d63792.png)
2、通过maven分析，版本已经修改成功
<img width="725" alt="image" src="https://user-images.githubusercontent.com/23491291/157006237-f12236ca-6bde-4024-9428-ebaacbf1317e.png">
3、但是通过工具分析出来的还是老版本
![image](https://user-images.githubusercontent.com/23491291/157006309-bfa811dc-7c5c-4958-813f-a4442b53793f.png)

**Comment by cxxxzy** [comment]
收到！非常感谢您的反馈，我们看下这个问题

**Comment by TopScrew** [comment]
您可能在本地修改依赖后没有再次触发安全扫描，导致依旧显示还是上次的扫描结果。请尝试再次触发扫描任务查看结果

**Comment by tianyunperfect** [comment]
> 您可能在本地修改依赖后没有再次触发安全扫描，导致依旧显示还是上次的扫描结果。请尝试再次触发扫描任务查看结果

嗯嗯，有可能，现在测试没有提示了，感谢！
